# Generated by Django 3.2.12 on 2022-04-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
